## Edit Distance

In [1]:
import pandas as pd
import numpy as np

In [2]:
def edit_dist(X, Y):
    # Lengths of the input strings
    m, n = len(X), len(Y)

    # Initialize the matrix with zeros
    T = [[0 for x in range(n + 1)] for y in range(m + 1)]

    # Initial matrix print
    print("-" * 50)
    print(np.array(T))
    print("-" * 50)

    # Initializing the first column
    for i in range(1, m + 1):
        T[i][0] = i
        print(np.array(T))
        print("-" * 50)

    # Initializing the first row
    for j in range(1, n + 1):
        T[0][j] = j
        print(np.array(T))
        print("-" * 50)

    # Filling in the rest of the matrix
    for i in range(1, m + 1):
        for j in range(1, n + 1):
            if X[i - 1] == Y[j - 1]:
                cost = 0
            else:
                cost = 2
            # Compute minimum cost for the operations
            T[i][j] = min(T[i - 1][j] + 1,     # deletion
                         T[i][j - 1] + 1,     # insertion
                         T[i - 1][j - 1] + cost)  # replacement

    # Final matrix print
    print(np.array(T))

    # Return the value in the bottom-right corner of the matrix
    return T[m][n]

In [3]:
edit_dist("Hello","World")

--------------------------------------------------
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
--------------------------------------------------
[[0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
--------------------------------------------------
[[0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [2 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
--------------------------------------------------
[[0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [2 0 0 0 0 0]
 [3 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
--------------------------------------------------
[[0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [2 0 0 0 0 0]
 [3 0 0 0 0 0]
 [4 0 0 0 0 0]
 [0 0 0 0 0 0]]
--------------------------------------------------
[[0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [2 0 0 0 0 0]
 [3 0 0 0 0 0]
 [4 0 0 0 0 0]
 [5 0 0 0 0 0]]
--------------------------------------------------
[[0 1 0 0 0 0]
 [1 0 0 0 0 0]
 [2 0 0 0 0 0]
 [3 0 0 0 0 0]
 [4 0 0 0 0 0]
 [5 0 0 0 0 0]]
------

8